name: "Setup Environment"
on:
  workflow_call:

#env:
#  BW_CLIENTID=${{ secrets.CLIENT_ID }}
#  BW_CLIENTSECRET=${{ secrets.CLIENT_SECRET }}

jobs:
  setup:
    name: "Setup"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Upgrade Pip
        run: pip install --upgrade pip
      - name: Install poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Install Playwright
        run: poetry run playwright install
      - name: Install Bitwarden CLI
        run: npm install -g @bitwarden/cli
      #- name: Setup Bitwarden CLI
      #  run: |
      #      bw config server ${{ secrets.VAULT_URL }}
      #      bw login --apikey