name: "Setup Environment"
description: "Sets up Python, install BW CLI"
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: latest
    - name: Upgrade Pip
      shell: bash
      run: pip install --upgrade pip
    - name: Install poetry
      shell: bash
      run: pip install poetry
    - name: Install dependencies
      shell: bash
      run: poetry install
    - name: Install Playwright
      shell: bash
      run: poetry run playwright install
    - name: Install Bitwarden CLI
      shell: bash
      run: npm install -g @bitwarden/cli