name: "Code Check"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: "Code Linting"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Upgrade Pip
        run: pip install --upgrade pip
      - name: Install poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Run PyLint
        run: poetry run pylint tests
